services:
  vue-celulares-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-celulares-frontend
    ports:
      - "5178:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - vue-app-network

networks:
  vue-app-network:
    driver: bridge

volumes:
  # Si necesitas persistir alg√∫n dato en el futuro
  app-data:
    driver: local